# Generated by Django 6.0 on 2026-01-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
