# Generated by Django 6.0 on 2026-01-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_is_subscription_active_company_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='FREE', max_length=20),
        ),
    ]
