# Generated by Django 6.0 on 2026-01-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='booking_buffer',
            field=models.PositiveIntegerField(default=15, help_text='Buffer time in minutes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
