# Generated by Django 6.0 on 2026-01-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_booking_buffer_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='closing_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='company',
            name='opening_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='company',
            name='booking_buffer',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
