# Generated by Django 6.0 on 2026-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_closing_time_company_opening_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
