# Generated by Django 6.0 on 2026-02-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('STARTER', 'Starter (Solo)'), ('PRO', 'Professional (Studio)'), ('ELITE', 'Studio Elite (Enterprise)')], default='STARTER', max_length=20),
        ),
    ]
