# Generated by Django 6.0 on 2026-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_company_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20),
        ),
    ]
