# Generated by Django 6.0 on 2026-03-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_company_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='stripe_customer_id',
            new_name='payfast_token',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stripe_subscription_id',
        ),
    ]
