"""
Django settings for bookingweb project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent.parent

# import datetime to manage sessions
from datetime import timedelta

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f72c9340552c3b1311141639b05a4b3e'

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '187.124.208.220', '.netictechnologies.com']  # Update this in production to specify allowed hosts


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'accounts',
    'core',
    'indemnity',
    'rest_framework',
    'bookingSite',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# 1. Unified CORS list (Delete the duplicate at the bottom of your file!)
CORS_ALLOWED_ORIGINS = [
    "http://187.124.208.220",
    "https://detailerflow.netictechnologies.com",
    "http://localhost:5173",  # For local Vite dev
]

CORS_ALLOW_CREDENTIALS = True

# 2. Unified CSRF list
CSRF_TRUSTED_ORIGINS = [
    "http://187.124.208.220",
    "https://detailerflow.netictechnologies.com",
    "http://localhost:5173",  # For local Vite dev
]

# CORS and CSRF
RENDER_EXTERNAL_URL = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_URL:
    CORS_ALLOWED_ORIGINS.append(f"https://{RENDER_EXTERNAL_URL}")
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_URL}")

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Trust X-Forwarded headers from reverse proxy (Nginx)
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# 3. Clean up Middleware (You had duplicates here too!)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # Move this to the TOP
    'whitenoise.middleware.WhiteNoiseMiddleware',    # Move this to SECOND
    'corsheaders.middleware.CorsMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # email-based auth works if USERNAME_FIELD='email'
)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),  # Lasts a full workday
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

ROOT_URLCONF = 'bookingweb.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates'),
#                  '/app/staticfiles',
#                     os.path.join(BASE_DIR, 'frontend_build')],
                 
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend_build'),
    os.path.join(BASE_DIR, 'media'),
]
WHITENOISE_INDEX_PAGE_SELF_CHECK = False
WHITENOISE_ROOT = os.path.join(BASE_DIR, 'frontend_build')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'frontend_build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Useful for dev
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookingweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use SQLite for local development, PostgreSQL for Docker
if os.environ.get('USE_POSTGRES'):
    DATABASES = {
        'default': dj_database_url.config(
            # If DATABASE_URL is set (Render/Production), use it.
            # Otherwise, fall back to your local SQLite.
            default=os.environ.get('DATABASE_URL', f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
            conn_max_age=600
        )
    }
else:
    # Local development with SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise is excellent for serving static files on Render
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (Images uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ASGI_APPLICATION = 'bookingweb.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}