PLAN_CONFIG = {
    'STARTER': {
        'monthly_bookings': 10,
        'max_users': 1,
        'max_images_before': 2,
        'max_images_after': 2,
        'max_image_width': 1280,
        'max_image_height': 720,
        'max_customers': 1000,
        'indemnity_history_limit': 0, # No history saved
        'buffer_timer': False,
        'price_usd': 0,
        'features': [
            '10 Monthly Bookings',
            '1 User Account',
            '2 Before / 2 After Photos (Up to 1280x720)',
            'Basic Digital Waivers',
            'Up to 1,000 Customers',
        ],
    },
    'PRO': {
        'monthly_bookings': 60,
        'max_users': 10,
        'max_images_before': 10,
        'max_images_after': 10,
        'max_image_width': 1920,
        'max_image_height': 1080,
        'max_customers': 5000,
        'indemnity_history_limit': 5,
        'buffer_timer': True,
        'price_usd': 129,
        'features': [
            '60 Monthly Bookings',
            '10 Team Members',
            '10 Before / 10 After HD Condition Captures (1920x1080)',
            'Store up to 5 Templates (1 Active)',
            'Manual template selection per booking',
            'Legally-Binding Asset Vault (Auto-Bound PDFs)',
            'Lightweight High-Speed Bay Architecture',
            'Buffer Timer Enabled',
            'Up to 5,000 Customers',
        ],
    },
    'ENTERPRISE': {
        'monthly_bookings': float('inf'),
        'max_users': 50,
        'max_images_before': 25,
        'max_images_after': 25,
        'max_image_width': 3840,
        'max_image_height': 2160,
        'max_customers': float('inf'), # Unlimited
        'indemnity_history_limit': 20,
        'max_linked_service_templates': 20,
        'storage_limit_gb': 100,
        'buffer_timer': True,
        'price_usd': 299,
        'features': [
            'Unlimited Bookings',
            '50 Team Members',
            '25 Before / 25 After 4K Condition Captures (3840x2160)',
            '20 Smart-Linked Service Templates',
            'Automatically binds the exact liability contract per booked service',
            '100GB Premium Cloud Vault Storage',
            'Enterprise Asset Vault + Forever Booking Sync',
            'Lifetime Legal History',
            'Priority Bay Support',
            'No-Lag Upload Pipeline for High-Res Logs',
            'Unlimited Customers',
        ],
    }
}