# Generated by Django 6.0 on 2026-01-25 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_username'),
        ('core', '0009_booking_cancelled_at_booking_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndemnityTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indemnity_templates', to='accounts.company')),
            ],
            options={
                'unique_together': {('company', 'version')},
            },
        ),
        migrations.CreateModel(
            name='IndemnityAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_user_agent', models.TextField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='indemnity_pdfs/')),
                ('document_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_indemnity', to='core.booking')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indemnity_agreements', to='accounts.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_indemnity_agreements', to='core.customer')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_agreements', to='indemnity.indemnitytemplate')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_photos', to='indemnity.indemnityagreement')),
            ],
        ),
    ]
