# Generated by Django 6.0.2 on 2026-02-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indemnity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehiclePhoto',
        ),
    ]
