# Generated by Django 6.0 on 2026-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indemnity', '0002_delete_vehiclephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='indemnityagreement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='indemnityagreement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
