# Generated by Django 6.0 on 2026-02-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indemnity', '0003_indemnityagreement_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indemnityagreement',
            name='signing_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
