# Generated by Django 6.0 on 2026-01-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_end_time',
            field=models.TimeField(null=True),
        ),
    ]
