# Generated by Django 6.0 on 2026-01-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_booking_booking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_end_time',
            field=models.TimeField(null=True),
        ),
    ]
