# Generated by Django 6.0 on 2026-01-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_booking_admin_signature_booking_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='admin_signature',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_authorized',
        ),
    ]
