# Generated by Django 6.0.2 on 2026-02-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_booking_admin_signature_booking_created_by_and_more'),
        ('indemnity', '0002_delete_vehiclephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_photos/')),
                ('photo_type', models.CharField(choices=[('BEFORE', 'Before Service'), ('AFTER', 'After Service')], default='BEFORE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='indemnity.indemnityagreement')),
            ],
        ),
    ]
