# Generated by Django 6.0.2 on 2026-02-03 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vehiclephoto'),
        ('indemnity', '0002_delete_vehiclephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclephoto',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_photos', to='indemnity.indemnityagreement'),
        ),
    ]
