# Generated by Django 6.0 on 2026-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_service_service_indemnity_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='location_type',
            field=models.CharField(choices=[('ONSITE', 'On-site at Company'), ('MOBILE', 'Mobile at Customer Location')], default='ONSITE', max_length=10),
        ),
    ]
